#Make for simulator
export ARCHS = x86_64
export TARGET = simulator:clang::13.0

INSTALL_TARGET_PROCESSES = SpringBoard
SUBPROJECTS += PXL/PXL_Battery

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/aggregate.mk